# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09abbecfa27bdb2c26cb1a62205a6681be9af547aad885f7d44c7000f45875ac299ed8bc6435552fa86da06564269c9f46fc9824858fd76e2963fdc2029801e5

test:
  secret_key_base: cbd560861fe9c39c6a6cb9b19bedb5414d984461dba8b2303a2b6a1562cd285aafa3991bbef307267a3f0edb297b5b2c6a0ba91c0fce4757220d187b1c48b97d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
